import './js/slider.js';
import './js/close-window.js';
import './js/buy-now-modal.js';
import './js/reviews-modal.js';
import './js/review.js';
import './js/subscribe-modal.js';
import './js/burger-menu.js';
import './js/scroll-up.js';
import './js/header.js';
import './js/dark-theme.js'
import '/js/features.js'