import "./js/slider.js";
import "./js/close-window.js";
import "./js/buy-now-modal.js";
import "./js/reviews-modal.js";
import "./js/subscribe-modal.js";
import "./js/burger-menu.js";
import "./js/features.js";
import "./js/scroll-up.js"
import "./js/header.js"
